version: 2.1

jobs:
  build_and_test:
    docker:
      - image: plugfox/flutter:3.29.3-android
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Check Flutter version
          command: flutter --version
      - run:
          name: Upgrade project dependencies
          command: |
            flutter pub upgrade
            cd android && ./gradlew wrapper --gradle-version=8.0.2 && cd ..
      - run:
          name: Check Flutter version
          command: flutter --version
      - run:
          name: Install dependencies
          command: flutter pub get
      - run:
          name: Analyze code
          command: flutter analyze
      - run:
          name: Run tests
          command: flutter test --coverage
      - run:
          name: Validate coverage file
          command: |
            if [ ! -f coverage/lcov.info ]; then
              echo "Coverage file not found!"
              exit 1
            fi
            echo "Coverage OK."

workflows:
  version: 2
  build_test:
    jobs:
      - build_and_test