version: 2.1

jobs:
  build:
    docker:
      - image: cirrusci/flutter:stable
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: flutter pub get

      - run:
          name: Static analysis (lint)
          command: flutter analyze

      - run:
          name: Run tests with coverage
          command: flutter test --coverage

      - run:
          name: Check coverage file
          command: |
            if [ ! -f coverage/lcov.info ]; then
              echo "Coverage file not found!"
              exit 1
            fi
            echo "Coverage OK."

      - run:
          name: Build debug APK
          command: flutter build apk --debug

      - run:
          name: List generated APK
          command: ls -lh build/app/outputs/flutter-apk/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
